//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFRS9_Menu_Set
    {
        public int Id { get; set; }
        public string User_Name { get; set; }
        public string Menu_Id { get; set; }
    
        public virtual IFRS9_Menu_Sub IFRS9_Menu_Sub { get; set; }
    }
}
