//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating_Info_SampleInfo
    {
        public string Bond_Number { get; set; }
        public string ISSUER_TICKER { get; set; }
        public string GUARANTOR_EQY_TICKER { get; set; }
        public string GUARANTOR_NAME { get; set; }
        public System.DateTime Report_Date { get; set; }
    }
}
